tools_directory = ".tools"

[jdk]
version = "*22.3.3"
distribution = "GraalVM CE 17"
post_extraction_commands = [
    "gu install native-image"
]

[maven]
version = "*3.9.3"
user_settings_file = "etc/m2/settings.xml"