name: Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-11.0

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2.1.1
      with:
        path: |
          ~/.m2/repository
        key: m2Repo

    - run: ./project-env-cli \
        --config-file=project-env.xml \
        --output-mode=GITHUB_ACTIONS \
        --output-file=github-actions-env.sh && \
        ./github-actions-env.sh

    - run: mvn -B package