name: Publish to WinGet
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: ProjectEnv.ProjectEnvCli
          installers-regex: '-setup\.exe$'
          token: ${{ secrets.WINGET_RELEASER_TOKEN }}
          version: ${{ github.event.release.tag_name || github.event.inputs.tag_name }}